version: "3"
services:
  frontend:
    build: ./frontend
    ports:
      - 3000:3000
    restart: always
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  ngrok:
    image: wernight/ngrok
    restart: always
    environment:
      NGROK_AUTH: $NGROK_AUTH_TOKEN
      NGROK_PROTOCOL: http
      NGROK_PORT: backend:3010
    ports:
      - 4040:4040
    networks:
      - default
    depends_on:
      - backend
  backend:
    build: ./backend
    ports:
      - 3010:3010
  storage:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: $MINIO_ROOT_USER
      MINIO_ROOT_PASSWORD: $MINIO_ROOT_PASSWORD
    volumes:
      - ./data:/data
    command: >
      server /data --console-address ":9001"

networks:
  default: null
